.

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,4 +1,3 @@
-# GitHub .github/workflows/terraform.yml
 name: Terraform
 
 on:
@@ -22,24 +21,20 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Checkout code
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Step 2: Setup Terraform
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.8.3
           terraform_wrapper: false
 
-      # Step 3: Set up Yandex Cloud service account key
       - name: Set up Yandex Cloud service account key
         working-directory: ./infra
         run: |
           echo "${{ secrets.YC_KEY_JSON }}" | base64 -d > ./authorized_key.json
 
-      # Step 4: Initialize Terraform
       - name: Initialize Terraform
         working-directory: ./infra
         run: terraform init -backend-config="access_key=${{ secrets.ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.SECRET_KEY }}"
@@ -47,7 +42,6 @@ jobs:
           ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
           SECRET_KEY: ${{ secrets.SECRET_KEY }}
 
-      # Step 5: Run Terraform Plan
       - name: Terraform Plan
         working-directory: ./infra
         if: ${{ github.event.inputs.action == 'plan' }}
@@ -57,8 +51,6 @@ jobs:
           TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
           TF_VAR_ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
 
-
-      # Step 6: Run Terraform Apply
       - name: Terraform Apply
         working-directory: ./infra
         if: ${{ github.event.inputs.action == 'apply' }}
@@ -73,10 +65,8 @@ jobs:
 
       - name: Debug cloud-init file
         working-directory: ./infra
-        run: |
-          cat init/vm-install.yml
+        run: cat init/vm-install.yml
 
-      # Step 7: Save External IP
       - name: Save External IP
         working-directory: ./infra
         if: ${{ github.event.inputs.action == 'apply' }}
@@ -89,16 +79,13 @@ jobs:
             exit 1
           fi
 
-
-
-
-      # Step 8: Notify on success (optional)
-      - name: Notify on success
+      - name: Notify on success apply
         if: success() && github.event.inputs.action == 'apply'
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_TO }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
+          parse_mode: MarkdownV2
           message: |
             ✅ *Deploy VM successful!* 🎉
 
@@ -110,7 +97,6 @@ jobs:
 
             👤 *Triggered by:* `${{ github.actor }}`
 
-      # Step 9: Run Destroy
       - name: Terraform Destroy
         working-directory: ./infra
         if: ${{ github.event.inputs.action == 'destroy' }}
@@ -120,13 +106,13 @@ jobs:
           TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
           TF_VAR_ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
 
-      # Step 8: Notify on success (optional)
-      - name: Notify on success
+      - name: Notify on success destroy
         if: success() && github.event.inputs.action == 'destroy'
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_TO }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
+          parse_mode: MarkdownV2
           message: |
             🔥 *Destroy VM successful!* ✅
 
@@ -137,7 +123,19 @@ jobs:
 
             👤 *Triggered by:* `${{ github.actor }}`
 
-      # Step 10: Run Deploy Workflow (optional)
+      - name: Save External IP
+        working-directory: ./infra
+        if: ${{ github.event.inputs.action == 'apply' }}
+        run: |
+          EXTERNAL_IP=$(terraform output -raw external_ip)
+          if [ -n "$EXTERNAL_IP" ]; then
+            echo "VM_ADDRESS=$EXTERNAL_IP" >> $GITHUB_ENV
+            echo "external_ip: $EXTERNAL_IP" > ../tests.yml
+          else
+            echo "Error: External IP is empty or not found"
+            exit 1
+          fi
+
       - name: Run Deploy Workflow
         if: success() && github.event.inputs.action == 'apply'
         run: |
